export default [
  { id: 1, cost: 2, name: "파이리 엉덩이" },
  { id: 2, cost: 2, name: "파이리 엉덩이" },
  { id: 3, cost: 2, name: "파이리 엉덩이" },
  { id: 4, cost: 2, name: "파이리 엉덩이" },
  { id: 5, cost: 2, name: "파이리 엉덩이" },
  { id: 6, cost: 2, name: "파이리 엉덩이" },
  { id: 7, cost: 2, name: "파이리 엉덩이" },
  { id: 8, cost: 2, name: "파이리 엉덩이" },
  { id: 9, cost: 2, name: "파이리 엉덩이" },
  { id: 10, cost: 2, name: "파이리 엉덩이" },
  { id: 11, cost: 2, name: "파이리 엉덩이" },
  { id: 12, cost: 2, name: "파이리 엉덩이" },
  { id: 13, cost: 2, name: "파이리 엉덩이" },
  { id: 14, cost: 2, name: "파이리 엉덩이" },
  { id: 15, cost: 2, name: "파이리 엉덩이" },
  { id: 16, cost: 2, name: "파이리 엉덩이" },
  { id: 17, cost: 2, name: "파이리 엉덩이" },
  { id: 18, cost: 2, name: "파이리 엉덩이" },
  { id: 19, cost: 2, name: "파이리 엉덩이" },
];
